version: '3'

services:
  db:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"

  profiles:
    image: ghcr.io/ghosts-network/profiles:latest
    ports:
      - "5400:80"
    depends_on:
      - db
    environment:
      - MONGO_CONNECTION=mongodb://db:27017/gprofiles
      - EVENTHUB_TYPE=rabbit
      - RABBIT_CONNECTION=amqp://guest:guest@rabbit:5672/
      - ASPNETCORE_ENVIRONMENT=Development
