version: '3'

services:
  db:
    image: mvertes/alpine-mongo

  api:
    build: .
    ports:
      - "5300:80"
    depends_on:
      - db
    environment:
      - MONGO_CONNECTION=mongodb://db:27017/gpublications
      - ASPNETCORE_ENVIRONMENT=Development
