name: Validate merge request

on:
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100
      - name: Install dependencies
        run: dotnet restore --nologo
      - name: Build
        run: |
          dotnet build --configuration Release --no-restore --nologo | tee ./log.txt
          grep '0 Warning(s)' ./log.txt
      - name: Test
        run: dotnet test --no-restore --nologo
