name: Validate merge request

on:
  pull_request:
    branches: [ master ]

env:
  MIN_COVERAGE: 20

jobs:
  unit-test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Install dotCover
        run: dotnet tool install JetBrains.dotCover.GlobalTool -g
      - name: Calculate coverage
        run: dotnet dotcover test --dcReportType=XML --dcFilters=-:module=GhostNetwork.Content.Domain.UnitTest
      - name: Validate coverage
        run: |
          total=$(grep -o 'CoveragePercent="[^"]*"' -m 1 dotCover.Output.xml | cut -c 18-19)
          echo $total
          if [ $total -lt $MIN_COVERAGE ]; then exit 1; fi
