name: Release beta version

on:
  workflow_dispatch:

jobs:

  unit-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.100
      - name: Install dependencies
        run: dotnet restore --nologo
      - name: Build
        run: |
          dotnet build --configuration Release --no-restore --nologo | tee ./log.txt
          grep '0 Warning(s)' ./log.txt
      - name: Test
        run: dotnet test --no-restore --nologo

  push-image:
    needs: unit-test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        run: |
          echo "${{ github.token }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
          docker buildx build --push \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/ghosts-network/content:${{ github.ref }}
